services:
  balance-service:
    build:
      context: ../balance-service
      dockerfile: Dockerfile
    container_name: balance-service-lab5
    environment:
      SPRING_RABBITMQ_HOST: 'rabbitmq'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://balance-db:5432/balance-db'
      AXON_AXONSERVER_SERVERS: 'axonserver:8124'
    networks:
      - balance-net
      - shared-net
    ports:
      - "8081:8080"
    depends_on:
      - balance-db
      - rabbitmq
      - axonserver 
    restart: unless-stopped

  balance-db:
    image: postgres:13.3
    container_name: balance-db-lab5
    networks:
      - balance-net
    environment:
      POSTGRES_DB: "balance-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./balance-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  user-service:
    build:
      context: ../user-service 
      dockerfile: Dockerfile 
    container_name: user-service-lab5
    environment:
      SPRING_DATA_REDIS_HOST: 'user-keydb'
      SPRING_RABBITMQ_HOST: 'rabbitmq'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://user-db:5432/apidemo-db'
    networks:
      - user-net
      - shared-net
    ports:
      - "8080:8080"
    depends_on:
      - user-keydb
      - user-db
      - rabbitmq
      - axonserver  
    restart: unless-stopped

  user-db:
    image: postgres:13.3
    container_name: user-db-lab5
    environment:
      POSTGRES_DB: "apidemo-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - user-net
    volumes:
      - ./user-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  user-keydb:
    image: "eqalpha/keydb"
    container_name: user-keydb-lab5
    command: "keydb-server /etc/keydb/redis.conf --server-threads 2"
    networks:
      - user-net
    volumes:
      - "./keydb-data:/data"
    restart: unless-stopped

  notification-service:
    build:
      context: ../notification-service  
      dockerfile: Dockerfile 
    container_name: notification-service-lab5
    networks:
      - shared-net
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    restart: unless-stopped

  axonserver:
    image: axoniq/axonserver
    container_name: axonserver-lab5
    ports:
      - "8024:8024"   
      - "8124:8124"   
    volumes:
      - ./axon-data:/axonserver/data
      - ./axon-events:/axonserver/events
      - ./axon-config:/axonserver/config
    environment:
      AXONIQ_AXONSERVER_NAME: axonserver
      AXONIQ_AXONSERVER_HOSTNAME: axonserver
      AXONIQ_AXONSERVER_DEVMODE_ENABLED: true
    restart: unless-stopped
    networks:
      - shared-net
    healthcheck:
      disable: true

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq-lab5
    networks:
      - shared-net
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_prometheus true" 
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  grafana-data:

networks:
  user-net: 
  balance-net: 
  shared-net: 
